import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressContentEditableWarning={true}>
      <body
        className={outfit.className}
      >
        <Provider>

        </Provider>
        {children}
      </body>
    </html>
  );
}
